import 'package:flutter/material.dart';

class LanguageProvider with ChangeNotifier {
  Locale _locale = const Locale('ar');
  
  Locale get locale => _locale;
  bool get isRTL => _locale.languageCode == 'ar';

  void toggleLanguage() {
    if (_locale.languageCode == 'en') {
      _locale = const Locale('ar');
    } else {
      _locale = const Locale('en');
    }
    notifyListeners();
  }

  static final Map<String, Map<String, String>> _translations = {
    'en': {
      'appName': 'FERRO',
      'login': 'Login',
      'signUp': 'Sign Up',
      'email': 'Email',
      'password': 'Password',
      'forgotPassword': 'Forgot Password?',
      'dontHaveAccount': "Don't have an account?",
      'alreadyHaveAccount': 'Already have an account?',
      'fullName': 'Full Name',
      'phone': 'Phone Number',
      'selectRole': 'Select Account Type',
      'continueBtn': 'Continue',
      'welcomeBack': 'Welcome Back',
      'requestService': 'Request Service',
      'myRequests': 'My Requests',
      'activeRequests': 'Active Requests',
      'completedRequests': 'Completed Requests',
      'totalSpent': 'Total Spent',
      'viewDetails': 'View Details',
      'towTruck': 'Tow Truck',
      'spareParts': 'Spare Parts',
      'workshop': 'Workshop',
      'inProgress': 'In Progress',
      'pending': 'Pending',
      'completed': 'Completed',
      'dashboard': 'Dashboard',
      'requests': 'Requests',
      'profile': 'Profile',
      'personalInfo': 'Personal Info',
      'businessInfo': 'Business Info',
      'documents': 'Documents',
      'email': 'Email',
      'phone': 'Phone',
      'edit': 'Edit',
      'vehicleType': 'Vehicle Type',
      'stats': 'Statistics',
      'customer': 'Customer',
      'driver': 'Driver',
      'supplier': 'Supplier',
      'emailHint': 'Enter your email',
      'passwordHint': 'Enter your password',
      'fullNameHint': 'Enter your full name',
      'phoneHint': 'Enter your phone number',
      'resetPasswordTitle': 'Reset Password',
      'resetPasswordMsg': 'Enter your email to receive a password reset link.',
      'resetLinkSent': 'Password reset link has been sent to your email.',
      'sendLink': 'Send Reset Link',
      'cancel': 'Cancel',
      'currency': 'LYD',
      'vehicleCondition': 'Vehicle Condition',
      'accident': 'Accident',
      'breakdown': 'Breakdown',
      'stuck': 'Stuck',
      'notes': 'Notes (Optional)',
      'uploadPhoto': 'Upload Photo',
      'engineType': 'Engine Type',
      'requiredPart': 'Required Part Name',
      'partCategory': 'Part Category',
      'engine': 'Engine',
      'electrical': 'Electrical',
      'body': 'Body',
      'suspension': 'Suspension',
      'vin': 'VIN Number',
      'preferredPartType': 'Preferred Part Type',
      'original': 'Original',
      'aftermarket': 'Aftermarket',
      'any': 'Any',
      'deliveryAddress': 'Delivery Address',
      'serviceType': 'Service Type',
      'simpleRepair': 'Simple Repair',
      'partReplacement': 'Part Replacement',
      'tireInflation': 'Tire Inflation',
      'batteryService': 'Battery Service',
      'oilFluids': 'Oil / Fluids',
      'problemDescription': 'Problem Description',
      'urgencyLevel': 'Urgency Level',
      'normalUrgency': 'Normal',
      'urgent': 'Urgent',
      'paymentMethod': 'Payment Method',
      'cash': 'Cash',
      'online': 'Online',
      'confirmRequest': 'Confirm Request',
      'sedan': 'Sedan',
      'suv': 'SUV',
      'pickup': 'Pickup',
      'van': 'Van',
      'running': 'Running',
      'notRunning': 'Not Running',
      'openTransport': 'Open Transport',
      'closedTransport': 'Closed Transport',
      'jumpStart': 'Jump Start',
      'flatTire': 'Flat Tire',
      'fuelDelivery': 'Fuel Delivery',
      'lockedCar': 'Locked Car',
      'carTransport': 'Car Transport',
      'roadsideAssistance': 'Roadside Assistance',
      'transportType': 'Transport Type',
      'assistanceType': 'Assistance Type',
    },
    'ar': {
      'appName': 'فِرّو',
      'login': 'تسجيل الدخول',
      'signUp': 'إنشاء حساب',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'forgotPassword': 'نسيت كلمة المرور؟',
      'dontHaveAccount': 'ليس لديك حساب؟',
      'alreadyHaveAccount': 'لديك حساب بالفعل؟',
      'fullName': 'الاسم الكامل',
      'phone': 'رقم الهاتف',
      'selectRole': 'اختر نوع الحساب',
      'continueBtn': 'متابعة',
      'welcomeBack': 'مرحباً بعودتك',
      'requestService': 'طلب خدمة',
      'myRequests': 'طلباتي',
      'activeRequests': 'الطلبات النشطة',
      'completedRequests': 'الطلبات المكتملة',
      'totalSpent': 'إجمالي المصروفات',
      'viewDetails': 'عرض التفاصيل',
      'towTruck': 'ساحبة',
      'spareParts': 'قطع غيار',
      'workshop': 'ورشة متنقلة',
      'towTruckService': 'طلب ساحبة',
      'sparePartsService': 'طلب قطع غيار',
      'workshopService': 'ورشة متنقلة (إصلاح في مكانك)',
      'inProgress': 'قيد التنفيذ',
      'pending': 'قيد الانتظار',
      'completed': 'مكتمل',
      'dashboard': 'لوحة التحكم',
      'requests': 'الطلبات',
      'profile': 'الملف الشخصي',
      'personalInfo': 'المعلومات الشخصية',
      'businessInfo': 'معلومات العمل',
      'documents': 'المستندات',
      'email': 'البريد الإلكتروني',
      'phone': 'رقم الهاتف',
      'edit': 'تعديل',
      'vehicleType': 'نوع المركبة',
      'stats': 'الإحصائيات',
      'customer': 'زبون',
      'driver': 'سائق',
      'supplier': 'مورد',
      'emailHint': 'أدخل بريدك الإلكتروني',
      'passwordHint': 'أدخل كلمة المرور',
      'fullNameHint': 'أدخل اسمك الكامل',
      'phoneHint': 'أدخل رقم هاتفك',
      'confirmPassword': 'تأكيد كلمة المرور',
      'confirmPasswordHint': 'أعد كتابة كلمة المرور',
      'city': 'المدينة',
      'cityHint': 'اختر المدينة',
      'vehicleBrand': 'ماركة المركبة',
      'vehicleBrandHint': 'مثل: تويوتا، مرسيدس',
      'vehicleModel': 'موديل المركبة',
      'vehicleModelHint': 'مثل: كامري، E300',
      'vehicleYear': 'سنة الصنع',
      'vehicleYearHint': 'مثال: 2024',
      'acceptTerms': 'أوافق على الشروط والأحكام',
      'driverType': 'نوع السائق',
      'towDriver': 'سائق ساحبة',
      'activeOrderConstraint': 'لا يمكنك طلب خدمة جديدة وهناك طلب قيد التنفيذ',
      'orderStatus_onTheWay': 'في الطريق',
      'orderStatus_loaded': 'تم تحميل السيارة',
      'orderStatus_delivered': 'وصلت السيارة',
      'orderStatus_pickedUp': 'استلم الطلبية',
      'orderStatus_arrived': 'وصل السائق',
      'priceOriginal': 'الأصلية',
      'priceChinese': 'الصينية',
      'priceAlternative': 'البديل',
      'setPrice': 'تحديد السعر',
      'waitingApproval': 'في انتظار الموافقة',
      'locationA': 'نقطة الانطلاق',
      'locationB': 'نقطة الوصول',
      'carBrand': 'ماركة السيارة',
      'carModel': 'موديل السيارة',
      'carYear': 'سنة الصنع',
      'personalCode': 'الرمز الشخصي',
      'deliveryDriver': 'سائق توصيل',
      'workingArea': 'منطقة العمل / النطاق',
      'workingAreaHint': 'مثال: شمال الرياض، جدة',
      'towTruckType': 'نوع السطحة',
      'normal': 'عادية',
      'flatbed': 'هيدروليك (فلاتيد)',
      'plateNumber': 'رقم اللوحة',
      'plateNumberHint': 'مثال: أ ب ج 1 2 3 4',
      'licenseNumber': 'رقم الرخصة',
      'licenseNumberHint': 'أدخل رقم رخصة القيادة',
      'uploadLicense': 'رفع صورة الرخصة',
      'uploadPhotos': 'رفع صور المركبة',
      'storeName': 'اسم المتجر / الورشة',
      'storeNameHint': 'أدخل اسم المحل التجاري',
      'storePhone': 'رقم هاتف المتجر',
      'ownerName': 'اسم المالك الكامل',
      'ownerPhone': 'رقم هاتف المالك',
      'storeLocation': 'موقع المتجر (تحديد على الخريطة)',
      'specialization': 'تخصص المورد (أنواع القطع / الماركات)',
      'workingDays': 'أيام العمل',
      'workingHours': 'ساعات العمل',
      'commercialRegister': 'رقم السجل التجاري',
      'uploadCR': 'رفع صورة السجل التجاري',
      'pendingReviewTitle': 'الحساب قيد المراجعة',
      'pendingReviewMsg': 'الحساب غير مفعل حالياً. بانتظار موافقة الإدارة المركزية.',
      'motorbike': 'دراجة نارية',
      'car': 'سيارة',
      'resetPasswordTitle': 'استعادة كلمة المرور',
      'resetPasswordMsg': 'أدخل بريدك الإلكتروني لاستلام رابط استعادة كلمة المرور.',
      'resetLinkSent': 'تم إرسال رابط استعادة كلمة المرور إلى بريدك الإلكتروني.',
      'sendLink': 'إرسال رابط الاستعادة',
      'cancel': 'إلغاء',
      'currency': 'د.ل',
      'vehicleCondition': 'حالة المركبة',
      'accident': 'حادث',
      'breakdown': 'عطل',
      'stuck': 'عالقة',
      'notes': 'ملاحظات (اختياري)',
      'uploadPhoto': 'رفع صورة',
      'engineType': 'نوع المحرك',
      'requiredPart': 'اسم القطعة المطلوبة',
      'partCategory': 'قسم القطعة',
      'engine': 'محرك',
      'electrical': 'كهرباء',
      'body': 'هيكل',
      'suspension': 'تعليق',
      'vin': 'رقم الهيكل (الشاسيه)',
      'preferredPartType': 'نوع القطعة المفضل',
      'original': 'أصلي',
      'aftermarket': 'تجاري',
      'any': 'أي نوع',
      'deliveryAddress': 'عنوان التوصيل',
      'serviceType': 'نوع الخدمة',
      'simpleRepair': 'إصلاح بسيط',
      'partReplacement': 'استبدال قطعة',
      'tireInflation': 'نفخ إطارات',
      'batteryService': 'خدمة بطارية',
      'oilFluids': 'زيوت وسوائل',
      'problemDescription': 'وصف المشكلة',
      'urgencyLevel': 'مستوى الاستعجال',
      'normalUrgency': 'عادي',
      'urgent': 'طارئ',
      'paymentMethod': 'طريقة الدفع',
      'cash': 'كاش',
      'online': 'أونلاين',
      'confirmRequest': 'تأكيد الطلب',
      'sedan': 'سيدان',
      'suv': 'دفع رباعي',
      'pickup': 'بيك أب',
      'van': 'فان',
      'running': 'تعمل',
      'notRunning': 'لا تعمل',
      'openTransport': 'سطحة مكشوفة',
      'closedTransport': 'سطحة مغلقة',
      'jumpStart': 'شحن بطارية',
      'flatTire': 'بنشر (تغيير إطار)',
      'fuelDelivery': 'توصيل وقود',
      'lockedCar': 'فتح سيارة مقفلة',
      'carTransport': 'نقل سيارات',
      'roadsideAssistance': 'مساعدة على الطريق',
      'transportType': 'نوع النقل',
      'assistanceType': 'نوع المساعدة',
    }
  };

  String translate(String key) {
    return _translations[_locale.languageCode]?[key] ?? key;
  }
}
